### ISSUE TITLE
请问这个qqbot 有发送视频的接口么

### ISSUE THREAD

**Issue by Pjt4Free** [corgiclub/ErGo#9]

**Comment by LuneZ99** [comment]
现在没有实现视频发送的功能。
我们使用的框架是基于 [mirai-api-http](https://github.com/project-mirai/mirai-api-http) 的，根据其提供的消息类型 [api](https://github.com/project-mirai/mirai-api-http/blob/master/docs/MessageType.md) ，没有视频消息功能（实际测试中体现为消息数据为空）。
我们暂时也没有对该底层框架进行进一步开发的计划。
